services:
  - type: static
    name: webblogopeden-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    plan: free
    autoDeploy: true

  - type: web
    name: webblogopeden-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
    plan: free
    autoDeploy: true
